project:
  type: website

website:
  title: "youtubequarto2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    css: styles/style.css
    js: styles/admin-script.js
    template: _templates/default.html
    toc: true



