project:
  type: website

website:
  title: "youtubequarto2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    css: style.css
    
    toc: true



